module.exports.userValidation = require("./user.validation");
module.exports.coachValidation =require("./coach.validation");
module.exports.playerValidation =require("./player.validation");
module.exports.eventValidation=require("./event.validation");
module.exports.leaguesValidation=require("./leagues.validation");
module.exports.sportValidation = require("./sport.validation");
module.exports.teamValidation = require("./team.validation");
module.exports.tournamentValidation = require("./tournament.validation");
module.exports.tokenValidation=require("./token.validation")