module.exports.User=require("./user.model");
module.exports.Coach=require("./coach.model");
module.exports.Player=require("./player.model");
module.exports.Leagues=require("./leagues.model");
module.exports.Event=require("./event.model");
module.exports.Sport = require("./sport.model");
module.exports.Team = require("./team.model");
module.exports.Tournament = require("./tournament.model");
module.exports.Token=require("./token.model")